package specgen

import (
	"go/parser"
	"go/token"
	"strings"
	"testing"

	"forgejo.coilysiren.me/coilyco-flight-deck/cli-guard/http/guardfile"
)

const fixture = `wrap ward-kdl ops forgejo {
	spec forgejo.swagger.v1.json
	base-url "forgejo.coilysiren.me/api/v1"
	auth header-token { header Authorization; prefix "token "; ssm "/forgejo/api-token" }
	can read repos
	can create repos
	can delete repos
}`

func TestRenderProducesValidGo(t *testing.T) {
	gf, err := guardfile.Parse([]byte(fixture))
	if err != nil {
		t.Fatalf("parse fixture: %v", err)
	}
	out, err := Render(gf, "forgejo.guardfile.kdl")
	if err != nil {
		t.Fatalf("Render: %v", err)
	}
	// gofmt'd output must parse as a Go file.
	if _, err := parser.ParseFile(token.NewFileSet(), "main.go", out, parser.AllErrors); err != nil {
		t.Fatalf("generated source does not parse: %v\n%s", err, out)
	}
	src := string(out)
	for _, want := range []string{
		"// Code generated by specverb-gen; DO NOT EDIT.",
		"//go:embed forgejo.guardfile.kdl",
		"//go:embed forgejo.swagger.lock.json",
		"var embeddedSpec0 []byte",
		`Name: "ward-kdl"`,
		"specverb.Mount(app",
		`"https://forgejo.coilysiren.me/swagger.v1.json", "WARD_KDL_OPS_FORGEJO_SPEC"`,
	} {
		if !strings.Contains(src, want) {
			t.Errorf("generated source missing %q", want)
		}
	}
}

func TestRenderSetMergesIntoOneBinary(t *testing.T) {
	const awsFixture = `wrap ward-kdl ops aws {
		spec aws.swagger.v1.json
		base-url "aws.example.com/api/v1"
		auth header-token { header Authorization; prefix "token "; ssm "/aws/api-token" }
		can list buckets
	}`
	fj, err := guardfile.Parse([]byte(fixture))
	if err != nil {
		t.Fatalf("parse forgejo fixture: %v", err)
	}
	aws, err := guardfile.Parse([]byte(awsFixture))
	if err != nil {
		t.Fatalf("parse aws fixture: %v", err)
	}
	out, err := RenderSet(
		[]*guardfile.Guardfile{fj, aws},
		[]string{"forgejo.guardfile.kdl", "aws.guardfile.kdl"},
	)
	if err != nil {
		t.Fatalf("RenderSet: %v", err)
	}
	if _, err := parser.ParseFile(token.NewFileSet(), "main.go", out, parser.AllErrors); err != nil {
		t.Fatalf("merged source does not parse: %v\n%s", err, out)
	}
	src := string(out)
	for _, want := range []string{
		"//go:embed forgejo.guardfile.kdl",
		"//go:embed aws.guardfile.kdl",
		"var embeddedGuardfile0 []byte",
		"var embeddedGuardfile1 []byte",
		`"WARD_KDL_OPS_FORGEJO_SPEC"`,
		`"WARD_KDL_OPS_AWS_SPEC"`,
		`Name: "ward-kdl"`,
	} {
		if !strings.Contains(src, want) {
			t.Errorf("merged source missing %q", want)
		}
	}
}

func TestRenderSetRejectsBinaryMismatch(t *testing.T) {
	const other = `wrap other ops aws {
		spec aws.swagger.v1.json
		base-url "aws.example.com/api/v1"
		auth header-token { header Authorization; prefix "token "; ssm "/aws/api-token" }
		can list buckets
	}`
	a, _ := guardfile.Parse([]byte(fixture))
	b, _ := guardfile.Parse([]byte(other))
	if _, err := RenderSet([]*guardfile.Guardfile{a, b}, []string{"a.kdl", "b.kdl"}); err == nil {
		t.Fatal("expected error when guardfiles disagree on binary name")
	}
}

func TestRenderRejectsEmptyGroup(t *testing.T) {
	if _, err := Render(&guardfile.Guardfile{}, "x.kdl"); err == nil {
		t.Fatal("expected error for a Guardfile with no group")
	}
}

func TestDeriveSpecURL(t *testing.T) {
	cases := map[string]string{
		"forgejo.coilysiren.me/api/v1":         "https://forgejo.coilysiren.me/swagger.v1.json",
		"https://forgejo.coilysiren.me/api/v1": "https://forgejo.coilysiren.me/swagger.v1.json",
	}
	for in, want := range cases {
		got, err := deriveSpecURL(in)
		if err != nil {
			t.Fatalf("deriveSpecURL(%q): %v", in, err)
		}
		if got != want {
			t.Errorf("deriveSpecURL(%q) = %q, want %q", in, got, want)
		}
	}
}

func TestPlanDerivesParams(t *testing.T) {
	gf, err := guardfile.Parse([]byte(fixture))
	if err != nil {
		t.Fatalf("parse fixture: %v", err)
	}
	p, err := Plan(gf, "forgejo.guardfile.kdl")
	if err != nil {
		t.Fatalf("Plan: %v", err)
	}
	want := Params{
		Binary:        "ward-kdl",
		GuardfileName: "forgejo.guardfile.kdl",
		SpecLockName:  "forgejo.swagger.lock.json",
		SpecURL:       "https://forgejo.coilysiren.me/swagger.v1.json",
		SpecEnvVar:    "WARD_KDL_OPS_FORGEJO_SPEC",
	}
	if p != want {
		t.Errorf("Plan = %+v, want %+v", p, want)
	}
}

func TestPlanRejectsEmptyGroup(t *testing.T) {
	if _, err := Plan(&guardfile.Guardfile{}, "x.kdl"); err == nil {
		t.Fatal("expected error for a Guardfile with no group")
	}
}
