// Package shim renders PATH shims for a consumer's protected binaries: a
// deny shim per binary that shadows the bare name. See docs/features-detail.md.
package shim

import (
	"fmt"
	"os/exec"
	"sort"
	"strings"

	"forgejo.coilysiren.me/coilyco-flight-deck/cli-guard/cli/hook"
)

// Spec is one rendered PATH shim. The consumer installs Body under Name on
// a PATH dir ahead of the real binary.
type Spec struct {
	// Name is the binary basename the shim shadows and the install filename.
	Name string
	// Body is the rendered POSIX-sh script. It has passed sh -n.
	Body string
}

// For expands a protected set into one deny shim per entry, sorted by Name.
// Every body is sh -n validated; a bad render fails the whole call.
func For(protected []hook.Protected) ([]Spec, error) {
	out := make([]Spec, 0, len(protected))
	seen := make(map[string]bool, len(protected))
	for _, p := range protected {
		name := hook.Basename(p.Name)
		if name == "" || seen[name] {
			continue
		}
		seen[name] = true
		body := renderDeny(name, recovery(p))
		if err := validateShellSyntax(body); err != nil {
			return nil, fmt.Errorf("shim: generated shim for %q failed sh -n: %w", name, err)
		}
		out = append(out, Spec{Name: name, Body: body})
	}
	sort.Slice(out, func(i, j int) bool { return out[i].Name < out[j].Name })
	return out, nil
}

// recovery resolves the shim's recovery sentence, mirroring hook precedence:
// explicit Hint, else synthesized from Wrappers, else none.
func recovery(p hook.Protected) string {
	switch {
	case p.Hint != "":
		return p.Hint
	case len(p.Wrappers) > 0:
		return fmt.Sprintf("route through an audited wrapper: %s.", strings.Join(p.Wrappers, ", "))
	default:
		return ""
	}
}

// renderDeny builds the deny-shim body. name and recovery are single-quoted
// so an unusual character cannot break the string or inject shell.
func renderDeny(name, recovery string) string {
	msg := fmt.Sprintf("cli-guard: direct `%s` is blocked.", name)
	if recovery != "" {
		msg += " Recovery: " + recovery
	}
	var b strings.Builder
	fmt.Fprintf(&b, `#!/bin/sh
# Auto-generated by cli-guard (shim). PATH shim for %s.
#
# This shim is UX, not the enforcement boundary. It shadows %s on PATH so a
# denied invocation gets a clear recovery message. A same-user agent can
# still reach the real binary by absolute path; the PreToolUse hook
# (basename-aware) and the sudo/ownership floor are the actual enforcement.
# See cli-guard #79.
printf '%%s\n' %s >&2
exit 2
`, sq(name), sq(name), sq(msg))
	return b.String()
}

// sq single-quotes s for POSIX sh, escaping embedded quotes via '\”.
func sq(s string) string {
	return "'" + strings.ReplaceAll(s, "'", `'\''`) + "'"
}

// validateShellSyntax parses body with sh -n (no execution). Mirrors
// lockdown's identical guard.
func validateShellSyntax(body string) error {
	cmd := exec.Command("sh", "-n")
	cmd.Stdin = strings.NewReader(body)
	out, err := cmd.CombinedOutput()
	if err != nil {
		return fmt.Errorf("%w: %s", err, string(out))
	}
	return nil
}
