// Package specgen renders a complete consumer `main.go` from a KDL Guardfile,
// so a consumer never hand-writes the specverb wiring. See docs/specverb.md.
package specgen

import (
	"bytes"
	"fmt"
	"go/format"
	"net/url"
	"strings"
	"text/template"

	"forgejo.coilysiren.me/coilyco-flight-deck/cli-guard/guardfile"
)

// params is the per-consumer data the template binds to, all derived from the
// Guardfile so the generated binary matches its declared command path + auth.
type params struct {
	Binary        string // binary name, e.g. ward-kdl (Guardfile group[0])
	GuardfileName string // embedded Guardfile filename, e.g. forgejo.guardfile.kdl
	SpecURL       string // where the Swagger doc is fetched on a cache miss
	SpecEnvVar    string // env var overriding the spec path, e.g. WARD_KDL_SPEC
	CacheDir      string // cache subdir under os.UserCacheDir, e.g. ward-kdl
}

// Render emits a gofmt'd `package main` wiring specverb.Mount for gf.
// guardfileName is the Guardfile's filename in the consumer dir (for the embed).
func Render(gf *guardfile.Guardfile, guardfileName string) ([]byte, error) {
	if gf == nil || len(gf.Group) == 0 {
		return nil, fmt.Errorf("specgen: Guardfile has no command group")
	}
	specURL, err := deriveSpecURL(gf.BaseURL)
	if err != nil {
		return nil, err
	}
	binary := gf.Group[0]
	p := params{
		Binary:        binary,
		GuardfileName: guardfileName,
		SpecURL:       specURL,
		SpecEnvVar:    strings.ToUpper(strings.ReplaceAll(binary, "-", "_")) + "_SPEC",
		CacheDir:      binary,
	}
	var buf bytes.Buffer
	if err := mainTemplate.Execute(&buf, p); err != nil {
		return nil, fmt.Errorf("specgen: execute template: %w", err)
	}
	out, err := format.Source(buf.Bytes())
	if err != nil {
		return nil, fmt.Errorf("specgen: gofmt generated source: %w", err)
	}
	return out, nil
}

// deriveSpecURL turns the Guardfile base-url into the Swagger fetch URL: the
// host root's /swagger.v1.json (Forgejo's convention), scheme defaulted to https.
func deriveSpecURL(baseURL string) (string, error) {
	if baseURL == "" {
		return "", fmt.Errorf("specgen: Guardfile has no base-url to derive the spec URL from")
	}
	if !strings.Contains(baseURL, "://") {
		baseURL = "https://" + baseURL
	}
	u, err := url.Parse(baseURL)
	if err != nil {
		return "", fmt.Errorf("specgen: parse base-url %q: %w", baseURL, err)
	}
	if u.Host == "" {
		return "", fmt.Errorf("specgen: base-url %q has no host", baseURL)
	}
	return u.Scheme + "://" + u.Host + "/swagger.v1.json", nil
}

// mainTemplate is the consumer main.go. It is gitignored output, so it carries
// the full self-contained wiring rather than deferring to a library.
var mainTemplate = template.Must(template.New("main").Parse(`// Code generated by specverb-gen; DO NOT EDIT.
// Source: {{.GuardfileName}}. Regenerate with the consumer's make target.
package main

import (
	"context"
	_ "embed"
	"errors"
	"fmt"
	"io"
	"net/http"
	"os"
	"path/filepath"
	"time"

	"forgejo.coilysiren.me/coilyco-flight-deck/cli-guard/audit"
	"forgejo.coilysiren.me/coilyco-flight-deck/cli-guard/config"
	"forgejo.coilysiren.me/coilyco-flight-deck/cli-guard/guardfile"
	"forgejo.coilysiren.me/coilyco-flight-deck/cli-guard/specverb"
	"forgejo.coilysiren.me/coilyco-flight-deck/cli-guard/verb"
	awsconfig "github.com/aws/aws-sdk-go-v2/config"
	"github.com/aws/aws-sdk-go-v2/service/ssm"
	"github.com/urfave/cli/v3"
)

//go:embed {{.GuardfileName}}
var embeddedGuardfile []byte

const specURL = "{{.SpecURL}}"

func main() {
	app := &cli.Command{Name: "{{.Binary}}", Usage: "spec-driven verbs generated by specverb-gen"}
	if err := mountOps(app); err != nil {
		fmt.Fprintln(os.Stderr, "{{.Binary}}:", err)
		os.Exit(1)
	}
	if err := app.Run(context.Background(), os.Args); err != nil {
		fmt.Fprintln(os.Stderr, "{{.Binary}}:", err)
		os.Exit(1)
	}
}

func mountOps(app *cli.Command) error {
	gf, err := guardfile.Parse(embeddedGuardfile)
	if err != nil {
		return fmt.Errorf("parse guardfile: %w", err)
	}
	spec, err := resolveSpec()
	if err != nil {
		return fmt.Errorf("resolve spec: %w", err)
	}
	return specverb.Mount(app, specverb.Config{
		Guardfile: gf,
		Spec:      spec,
		Wrap:      wrapWith(auditWriter()),
		Token:     ssmTokenResolver,
	})
}

func resolveSpec() ([]byte, error) {
	path := os.Getenv("{{.SpecEnvVar}}")
	if path == "" {
		cache, err := os.UserCacheDir()
		if err != nil {
			return nil, err
		}
		path = filepath.Join(cache, "{{.CacheDir}}", "forgejo.swagger.v1.json")
	}
	if b, err := os.ReadFile(path); err == nil {
		return b, nil
	}
	fmt.Fprintf(os.Stderr, "{{.Binary}}: fetching spec -> %s\n", path)
	b, err := fetchSpec(specURL)
	if err != nil {
		return nil, err
	}
	if err := os.MkdirAll(filepath.Dir(path), 0o750); err == nil {
		_ = os.WriteFile(path, b, 0o600)
	}
	return b, nil
}

func fetchSpec(u string) ([]byte, error) {
	client := &http.Client{Timeout: 30 * time.Second}
	resp, err := client.Get(u)
	if err != nil {
		return nil, err
	}
	defer func() { _ = resp.Body.Close() }()
	if resp.StatusCode != http.StatusOK {
		return nil, fmt.Errorf("GET %s -> %s", u, resp.Status)
	}
	return io.ReadAll(resp.Body)
}

func auditWriter() *audit.Writer {
	path, err := config.DefaultAuditPath()
	if err != nil {
		fmt.Fprintf(os.Stderr, "{{.Binary}}: fatal: resolve audit path: %v\n", err)
		os.Exit(2)
	}
	w := audit.NewWriter(path)
	if err := w.Preflight(); err != nil {
		fmt.Fprintf(os.Stderr, "{{.Binary}}: fatal: %v\n", err)
		os.Exit(2)
	}
	return w
}

func wrapWith(w *audit.Writer) func(verb.Spec) cli.ActionFunc {
	return func(s verb.Spec) cli.ActionFunc { return verb.Wrap(s, w) }
}

func ssmTokenResolver(ctx context.Context, ssmPath string) (string, error) {
	cfg, err := awsconfig.LoadDefaultConfig(ctx)
	if err != nil {
		return "", fmt.Errorf("load aws config: %w", err)
	}
	out, err := ssm.NewFromConfig(cfg).GetParameter(ctx, &ssm.GetParameterInput{
		Name:           &ssmPath,
		WithDecryption: boolPtr(true),
	})
	if err != nil {
		return "", fmt.Errorf("ssm get-parameter %s: %w", ssmPath, err)
	}
	if out.Parameter == nil || out.Parameter.Value == nil {
		return "", errors.New("ssm get-parameter returned no value")
	}
	return *out.Parameter.Value, nil
}

func boolPtr(b bool) *bool { return &b }
`))
