package specgen

import (
	"go/parser"
	"go/token"
	"strings"
	"testing"

	"forgejo.coilysiren.me/coilyco-flight-deck/cli-guard/guardfile"
)

const fixture = `wrap ward-kdl ops forgejo {
	spec forgejo.swagger.v1.json
	base-url "forgejo.coilysiren.me/api/v1"
	auth header-token { header Authorization; prefix "token "; ssm "/forgejo/api-token" }
	can read repos
	can create repos
	can delete repos
}`

func TestRenderProducesValidGo(t *testing.T) {
	gf, err := guardfile.Parse([]byte(fixture))
	if err != nil {
		t.Fatalf("parse fixture: %v", err)
	}
	out, err := Render(gf, "forgejo.guardfile.kdl")
	if err != nil {
		t.Fatalf("Render: %v", err)
	}
	// gofmt'd output must parse as a Go file.
	if _, err := parser.ParseFile(token.NewFileSet(), "main.go", out, parser.AllErrors); err != nil {
		t.Fatalf("generated source does not parse: %v\n%s", err, out)
	}
	src := string(out)
	for _, want := range []string{
		"// Code generated by specverb-gen; DO NOT EDIT.",
		"//go:embed forgejo.guardfile.kdl",
		"//go:embed forgejo.swagger.lock.json",
		"var embeddedSpec []byte",
		`Name: "ward-kdl"`,
		"specverb.Mount(app",
		`os.Getenv("WARD_KDL_SPEC")`,
		`const specURL = "https://forgejo.coilysiren.me/swagger.v1.json"`,
	} {
		if !strings.Contains(src, want) {
			t.Errorf("generated source missing %q", want)
		}
	}
}

func TestRenderRejectsEmptyGroup(t *testing.T) {
	if _, err := Render(&guardfile.Guardfile{}, "x.kdl"); err == nil {
		t.Fatal("expected error for a Guardfile with no group")
	}
}

func TestDeriveSpecURL(t *testing.T) {
	cases := map[string]string{
		"forgejo.coilysiren.me/api/v1":         "https://forgejo.coilysiren.me/swagger.v1.json",
		"https://forgejo.coilysiren.me/api/v1": "https://forgejo.coilysiren.me/swagger.v1.json",
	}
	for in, want := range cases {
		got, err := deriveSpecURL(in)
		if err != nil {
			t.Fatalf("deriveSpecURL(%q): %v", in, err)
		}
		if got != want {
			t.Errorf("deriveSpecURL(%q) = %q, want %q", in, got, want)
		}
	}
}
